# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  # mariadb:
  #   image: docker.io/bitnami/mariadb:11.3
  #   volumes:
  #     - 'mariadb_data:/bitnami/mariadb'
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_wordpress
  #     - MARIADB_DATABASE=bitnami_wordpress
  # wordpress:
  #   image: docker.io/bitnami/wordpress:6
  #   ports:
  #     - '81:8080'
  #     - '443:8443'
  #   volumes:
  #     - 'wordpress_data:/bitnami/wordpress'
  #   depends_on:
  #     - mariadb
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - WORDPRESS_DATABASE_HOST=mariadb
  #     - WORDPRESS_DATABASE_PORT_NUMBER=3306
  #     - WORDPRESS_DATABASE_USER=bn_wordpress
  #     - WORDPRESS_DATABASE_NAME=bitnami_wordpress
  apache:
    build: php
    ports:
      - '80:80'
    volumes:
      - './phpFile:/var/www/html'
    restart: unless-stopped
  mysql:
    image: docker.io/bitnami/mysql
    hostname: springdb
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6 
  spring:
    build: Proyecto-Fin-Grado
    hostname: springProyect #sustituir por localhost
    depends_on:
      - mysql
    ports: 
      - '8080:8080'
    restart: unless-stopped       
volumes:
  mariadb_data:
  wordpress_data:
  mysql_data: