version: '2'
services:
  apache:
    build: php
    ports:
      - '80:80'
    volumes:
      - './phpFile:/var/www/html'
    restart: unless-stopped
  mysql:
    image: docker.io/bitnami/mysql
    hostname: springdb
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
  spring:
    build: Proyecto-Fin-Grado    
    hostname: springProyect #sustituir por localhost/springProyect
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    restart: unless-stopped
volumes:
  mysql_data:
